#!/usr/bin/env bash
# Installs and configures HAproxy on webserver 3, distributes requests
# using a roundrobin algorithm

 echo "
# 54.237.116.155 49141-web-01
# 52.87.220.88 49141-web-02
# 34.239.107.98 49141-lb-01
# " | sudo tee -a /etc/hosts

sudo apt-get update
sudo apt-get upgrade

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 49141-web-01 54.237.116.155:80 check
    server 49141-web-02 52.87.220.88:80 check
"
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
~                           
