#!/usr/bin/env bash
# Using your debugging skills, find out whats keeping
# your Ubuntu container from Nginx installation from listening on port 80.
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
