#!/usr/bin/env bash
# Display "Best School" 10 times but for the 9th iteration display "Best School" and then "hi" on a new line
i=0
while [ "$i" -le 8 ];
do
	echo "Best School"
	i=$((i+1))
	if [ "$i" -eq 8 ];
	then
        	echo "Hi"
	fi
done

