#!/usr/bin/env bash
# display if "school" file exist or not 

FILE="school"
if [ -e "$FILE" ];
then
	echo "school file exist"
	if [ -s "$FILE" ];
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "FILE" ];
	then 
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
