#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# 1- localhost resolves to 127.0.0.2
# 2- facebook.com resolves to 8.8.8.8.
# 3- The checker is running on Docker, so make sure to read this
# configures Ubuntu server
oldfile="/etc/hosts"
newfile="$HOME/hosts.new"
sudo cp "$oldfile" "$newfile"
sudo sed -i s/127.0.0.1/127.0.0.2/ "$newfile"
echo "8.8.8.8	facebook.com" >> "$newfile"
sudo cp -f "$newfile" "$oldfile"
