#!/usr/bin/env bash                                                                                                                                                                             
# ash script that accepts one argument and run the whoami command                                                                                                                               
# under the user passed as an argument                                                                                                                                                          
sudo -u "$1" "whoami" 
